; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=i386-linux-gnu -global-isel -mattr=-sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=NO-SSE
; RUN: llc -mtriple=i386-linux-gnu -global-isel -mattr=+sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=SSE
; RUN: llc -mtriple=i386-linux-gnu -global-isel -mattr=+avx     -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX
; RUN: llc -mtriple=i386-linux-gnu -global-isel -mattr=+avx512f -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=AVX512

define ptr @inttoptr_p0_s32(i32 %val) {
; CHECK-LABEL: inttoptr_p0_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl 4(%esp), %eax
; CHECK-NEXT:    retl
; NO-SSE-LABEL: inttoptr_p0_s32:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; NO-SSE-NEXT:    retl
;
; SSE-LABEL: inttoptr_p0_s32:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SSE-NEXT:    retl
;
; AVX-LABEL: inttoptr_p0_s32:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    movl {{[0-9]+}}(%esp), %eax
; AVX-NEXT:    retl
;
; AVX512-LABEL: inttoptr_p0_s32:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    movl {{[0-9]+}}(%esp), %eax
; AVX512-NEXT:    retl
entry:
  %0 = inttoptr i32 %val to ptr
  ret ptr %0
}

define <4 x ptr> @inttoptr_v4p0_v4s32(<4 x i32> %val) {
; NO-SSE-LABEL: inttoptr_v4p0_v4s32:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    pushl %edi
; NO-SSE-NEXT:    .cfi_def_cfa_offset 8
; NO-SSE-NEXT:    pushl %esi
; NO-SSE-NEXT:    .cfi_def_cfa_offset 12
; NO-SSE-NEXT:    .cfi_offset %esi, -12
; NO-SSE-NEXT:    .cfi_offset %edi, -8
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %edx
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %esi
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %edi
; NO-SSE-NEXT:    movl %ecx, (%eax)
; NO-SSE-NEXT:    movl %edx, 4(%eax)
; NO-SSE-NEXT:    movl %esi, 8(%eax)
; NO-SSE-NEXT:    movl %edi, 12(%eax)
; NO-SSE-NEXT:    popl %esi
; NO-SSE-NEXT:    .cfi_def_cfa_offset 8
; NO-SSE-NEXT:    popl %edi
; NO-SSE-NEXT:    .cfi_def_cfa_offset 4
; NO-SSE-NEXT:    retl
;
; SSE-LABEL: inttoptr_v4p0_v4s32:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    pushl %edi
; SSE-NEXT:    .cfi_def_cfa_offset 8
; SSE-NEXT:    pushl %esi
; SSE-NEXT:    .cfi_def_cfa_offset 12
; SSE-NEXT:    .cfi_offset %esi, -12
; SSE-NEXT:    .cfi_offset %edi, -8
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %edx
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %esi
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %edi
; SSE-NEXT:    movl %ecx, (%eax)
; SSE-NEXT:    movl %edx, 4(%eax)
; SSE-NEXT:    movl %esi, 8(%eax)
; SSE-NEXT:    movl %edi, 12(%eax)
; SSE-NEXT:    popl %esi
; SSE-NEXT:    .cfi_def_cfa_offset 8
; SSE-NEXT:    popl %edi
; SSE-NEXT:    .cfi_def_cfa_offset 4
; SSE-NEXT:    retl
;
; AVX-LABEL: inttoptr_v4p0_v4s32:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retl
;
; AVX512-LABEL: inttoptr_v4p0_v4s32:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retl
entry:
  %0 = inttoptr <4 x i32> %val to <4 x ptr>
  ret <4 x ptr> %0
}

define <8 x ptr> @inttoptr_v8p0_v8s32(<8 x i32> %val) {
; NO-SSE-LABEL: inttoptr_v8p0_v8s32:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; NO-SSE-NEXT:    movl %ecx, (%eax)
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; NO-SSE-NEXT:    movl %ecx, 4(%eax)
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; NO-SSE-NEXT:    movl %ecx, 8(%eax)
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; NO-SSE-NEXT:    movl %ecx, 12(%eax)
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; NO-SSE-NEXT:    movl %ecx, 16(%eax)
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; NO-SSE-NEXT:    movl %ecx, 20(%eax)
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; NO-SSE-NEXT:    movl %ecx, 24(%eax)
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; NO-SSE-NEXT:    movl %ecx, 28(%eax)
; NO-SSE-NEXT:    retl
;
; SSE-LABEL: inttoptr_v8p0_v8s32:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SSE-NEXT:    movl %ecx, (%eax)
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SSE-NEXT:    movl %ecx, 4(%eax)
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SSE-NEXT:    movl %ecx, 8(%eax)
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SSE-NEXT:    movl %ecx, 12(%eax)
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SSE-NEXT:    movl %ecx, 16(%eax)
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SSE-NEXT:    movl %ecx, 20(%eax)
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SSE-NEXT:    movl %ecx, 24(%eax)
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SSE-NEXT:    movl %ecx, 28(%eax)
; SSE-NEXT:    retl
;
; AVX-LABEL: inttoptr_v8p0_v8s32:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retl
;
; AVX512-LABEL: inttoptr_v8p0_v8s32:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retl
entry:
  %0 = inttoptr <8 x i32> %val to <8 x ptr>
  ret <8 x ptr> %0
}
