; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel -mattr=-sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=NO-SSE
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel                 -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=SSE
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel -mattr=+avx     -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel -mattr=+avx512f -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=AVX512

define ptr @inttoptr_p0_s64(i64 %val) {
; NO-SSE-LABEL: inttoptr_p0_s64:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movq %rdi, %rax
; NO-SSE-NEXT:    retq
;
; SSE-LABEL: inttoptr_p0_s64:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    movq %rdi, %rax
; SSE-NEXT:    retq
;
; AVX-LABEL: inttoptr_p0_s64:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    movq %rdi, %rax
; AVX-NEXT:    retq
;
; AVX512-LABEL: inttoptr_p0_s64:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    movq %rdi, %rax
; AVX512-NEXT:    retq
entry:
  %0 = inttoptr i64 %val to ptr
  ret ptr %0
}

define <2 x ptr> @inttoptr_v2p0_v2s64(<2 x i64> %val) {
; CHECK-LABEL: inttoptr_v2p0_v2s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    retq
; NO-SSE-LABEL: inttoptr_v2p0_v2s64:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movq %rdi, %rax
; NO-SSE-NEXT:    movq %rsi, %rdx
; NO-SSE-NEXT:    retq
;
; SSE-LABEL: inttoptr_v2p0_v2s64:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retq
;
; AVX-LABEL: inttoptr_v2p0_v2s64:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retq
;
; AVX512-LABEL: inttoptr_v2p0_v2s64:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retq
entry:
  %0 = inttoptr <2 x i64> %val to <2 x ptr>
  ret <2 x ptr> %0
}

define <4 x ptr> @inttoptr_v4p0_v4s64(<4 x i64> %val) {
; NO-SSE-LABEL: inttoptr_v4p0_v4s64:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movq %rdi, %rax
; NO-SSE-NEXT:    movq %rsi, (%rdi)
; NO-SSE-NEXT:    movq %rdx, 8(%rdi)
; NO-SSE-NEXT:    movq %rcx, 16(%rdi)
; NO-SSE-NEXT:    movq %r8, 24(%rdi)
; NO-SSE-NEXT:    retq
;
; SSE-LABEL: inttoptr_v4p0_v4s64:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retq
;
; AVX-LABEL: inttoptr_v4p0_v4s64:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retq
;
; AVX512-LABEL: inttoptr_v4p0_v4s64:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retq
entry:
  %0 = inttoptr <4 x i64> %val to <4 x ptr>
  ret <4 x ptr> %0
}

define <8 x ptr> @inttoptr_v8p0_v8s64(<8 x i64> %val) {
; NO-SSE-LABEL: inttoptr_v8p0_v8s64:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movq %rdi, %rax
; NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %r10
; NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %r11
; NO-SSE-NEXT:    movq %rsi, (%rax)
; NO-SSE-NEXT:    movq %rdx, 8(%rax)
; NO-SSE-NEXT:    movq %rcx, 16(%rax)
; NO-SSE-NEXT:    movq %r8, 24(%rax)
; NO-SSE-NEXT:    movq %r9, 32(%rax)
; NO-SSE-NEXT:    movq %rdi, 40(%rax)
; NO-SSE-NEXT:    movq %r10, 48(%rax)
; NO-SSE-NEXT:    movq %r11, 56(%rax)
; NO-SSE-NEXT:    retq
;
; SSE-LABEL: inttoptr_v8p0_v8s64:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retq
;
; AVX-LABEL: inttoptr_v8p0_v8s64:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retq
;
; AVX512-LABEL: inttoptr_v8p0_v8s64:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retq
entry:
  %0 = inttoptr <8 x i64> %val to <8 x ptr>
  ret <8 x ptr> %0
}
