; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=i386-linux-gnu -global-isel -mattr=-sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=SCALAR
; RUN: llc -mtriple=i386-linux-gnu -global-isel                 -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=SCALAR
; RUN: llc -mtriple=i386-linux-gnu -global-isel -mattr=+avx     -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=SCALAR
; RUN: llc -mtriple=i386-linux-gnu -global-isel -mattr=+avx512f -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=SCALAR

define i1 @ptrtoint_s1_p0(ptr %p) {
; SCALAR-LABEL: ptrtoint_s1_p0:
; SCALAR:       # %bb.0: # %entry
; SCALAR-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SCALAR-NEXT:    # kill: def $al killed $al killed $eax
; SCALAR-NEXT:    retl
entry:
  %0 = ptrtoint ptr %p to i1
  ret i1 %0
}

define i8 @ptrtoint_s8_p0(ptr %p) {
; SCALAR-LABEL: ptrtoint_s8_p0:
; SCALAR:       # %bb.0: # %entry
; SCALAR-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SCALAR-NEXT:    # kill: def $al killed $al killed $eax
; SCALAR-NEXT:    retl
entry:
  %0 = ptrtoint ptr %p to i8
  ret i8 %0
}

define i16 @ptrtoint_s16_p0(ptr %p) {
; SCALAR-LABEL: ptrtoint_s16_p0:
; SCALAR:       # %bb.0: # %entry
; SCALAR-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SCALAR-NEXT:    # kill: def $ax killed $ax killed $eax
; SCALAR-NEXT:    retl
entry:
  %0 = ptrtoint ptr %p to i16
  ret i16 %0
}

define i32 @ptrtoint_s32_p0(ptr %p) {
; SCALAR-LABEL: ptrtoint_s32_p0:
; SCALAR:       # %bb.0: # %entry
; SCALAR-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SCALAR-NEXT:    retl
entry:
  %0 = ptrtoint ptr %p to i32
  ret i32 %0
}
