; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel -mattr=-sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=SCALAR,NO-SSE
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel                 -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=SCALAR,SSE
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel -mattr=+avx     -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=SCALAR,AVX
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel -mattr=+avx512f -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=SCALAR,AVX512

define i1 @ptrtoint_s1_p0(ptr %p) {
; SCALAR-LABEL: ptrtoint_s1_p0:
; SCALAR:       # %bb.0: # %entry
; SCALAR-NEXT:    movq %rdi, %rax
; SCALAR-NEXT:    # kill: def $al killed $al killed $rax
; SCALAR-NEXT:    retq
entry:
  %0 = ptrtoint ptr %p to i1
  ret i1 %0
}

define i8 @ptrtoint_s8_p0(ptr %p) {
; SCALAR-LABEL: ptrtoint_s8_p0:
; SCALAR:       # %bb.0: # %entry
; SCALAR-NEXT:    movq %rdi, %rax
; SCALAR-NEXT:    # kill: def $al killed $al killed $rax
; SCALAR-NEXT:    retq
entry:
  %0 = ptrtoint ptr %p to i8
  ret i8 %0
}

define i16 @ptrtoint_s16_p0(ptr %p) {
; SCALAR-LABEL: ptrtoint_s16_p0:
; SCALAR:       # %bb.0: # %entry
; SCALAR-NEXT:    movq %rdi, %rax
; SCALAR-NEXT:    # kill: def $ax killed $ax killed $rax
; SCALAR-NEXT:    retq
entry:
  %0 = ptrtoint ptr %p to i16
  ret i16 %0
}

define i32 @ptrtoint_s32_p0(ptr %p) {
; SCALAR-LABEL: ptrtoint_s32_p0:
; SCALAR:       # %bb.0: # %entry
; SCALAR-NEXT:    movq %rdi, %rax
; SCALAR-NEXT:    # kill: def $eax killed $eax killed $rax
; SCALAR-NEXT:    retq
entry:
  %0 = ptrtoint ptr %p to i32
  ret i32 %0
}

define i64 @ptrtoint_s64_p0(ptr %p) {
; SCALAR-LABEL: ptrtoint_s64_p0:
; SCALAR:       # %bb.0: # %entry
; SCALAR-NEXT:    movq %rdi, %rax
; SCALAR-NEXT:    retq
entry:
  %0 = ptrtoint ptr %p to i64
  ret i64 %0
}

define <2 x i1> @ptrtoint_v2s1_v2p0(<2 x ptr> %p) {
; NO-SSE-LABEL: ptrtoint_v2s1_v2p0:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movq %rdi, %rax
; NO-SSE-NEXT:    movq %rsi, %rdx
; NO-SSE-NEXT:    # kill: def $al killed $al killed $rax
; NO-SSE-NEXT:    # kill: def $dl killed $dl killed $rdx
; NO-SSE-NEXT:    retq
;
; SSE-LABEL: ptrtoint_v2s1_v2p0:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retq
;
; AVX-LABEL: ptrtoint_v2s1_v2p0:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retq
;
; AVX512-LABEL: ptrtoint_v2s1_v2p0:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retq
entry:
  %0 = ptrtoint <2 x ptr> %p to <2 x i1>
  ret <2 x i1> %0
}

define <2 x i64> @ptrtoint_v2s64_v2p0(<2 x ptr> %p) {
; NO-SSE-LABEL: ptrtoint_v2s64_v2p0:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movq %rdi, %rax
; NO-SSE-NEXT:    movq %rsi, %rdx
; NO-SSE-NEXT:    retq
;
; SSE-LABEL: ptrtoint_v2s64_v2p0:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retq
;
; AVX-LABEL: ptrtoint_v2s64_v2p0:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retq
;
; AVX512-LABEL: ptrtoint_v2s64_v2p0:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retq
entry:
  %0 = ptrtoint <2 x ptr> %p to <2 x i64>
  ret <2 x i64> %0
}

define <4 x i64> @ptrtoint_v4s64_v4p0(<4 x ptr> %p) {
; NO-SSE-LABEL: ptrtoint_v4s64_v4p0:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movq %rdi, %rax
; NO-SSE-NEXT:    movq %rsi, (%rdi)
; NO-SSE-NEXT:    movq %rdx, 8(%rdi)
; NO-SSE-NEXT:    movq %rcx, 16(%rdi)
; NO-SSE-NEXT:    movq %r8, 24(%rdi)
; NO-SSE-NEXT:    retq
;
; SSE-LABEL: ptrtoint_v4s64_v4p0:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retq
;
; AVX-LABEL: ptrtoint_v4s64_v4p0:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retq
;
; AVX512-LABEL: ptrtoint_v4s64_v4p0:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retq
entry:
  %0 = ptrtoint <4 x ptr> %p to <4 x i64>
  ret <4 x i64> %0
}

define <8 x i64> @ptrtoint_v8s64_v8p0(<8 x ptr> %p) {
; NO-SSE-LABEL: ptrtoint_v8s64_v8p0:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movq %rdi, %rax
; NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %r10
; NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %r11
; NO-SSE-NEXT:    movq %rsi, (%rax)
; NO-SSE-NEXT:    movq %rdx, 8(%rax)
; NO-SSE-NEXT:    movq %rcx, 16(%rax)
; NO-SSE-NEXT:    movq %r8, 24(%rax)
; NO-SSE-NEXT:    movq %r9, 32(%rax)
; NO-SSE-NEXT:    movq %rdi, 40(%rax)
; NO-SSE-NEXT:    movq %r10, 48(%rax)
; NO-SSE-NEXT:    movq %r11, 56(%rax)
; NO-SSE-NEXT:    retq
;
; SSE-LABEL: ptrtoint_v8s64_v8p0:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retq
;
; AVX-LABEL: ptrtoint_v8s64_v8p0:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retq
;
; AVX512-LABEL: ptrtoint_v8s64_v8p0:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retq
entry:
  %0 = ptrtoint <8 x ptr> %p to <8 x i64>
  ret <8 x i64> %0
}
