; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple=aarch64 -mattr=+fprcvt -mattr=+fullfp16 -mattr=+neon -mattr=+sve -force-streaming-compatible | FileCheck %s --check-prefixes=CHECK-FPRCVT-SVE
; RUN: llc < %s -mtriple=aarch64 -mattr=+fprcvt -mattr=+fullfp16 -mattr=+neon -mattr=+sme -force-streaming | FileCheck %s --check-prefixes=CHECK-FPRCVT-SME

; These tests are a smaller sets of tests that are in fptoui-sat-vector-fprcvt.ll
; but running with streaming feature

;
; Float to unsigned 32-bit -- Vector size variation
;

define <1 x i32> @test_unsigned_v1f32_v1i32(<1 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v1f32_v1i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v1f32_v1i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <1 x i32> @llvm.fptoui.sat.v1f32.v1i32(<1 x float> %f)
    ret <1 x i32> %x
}

define <2 x i32> @test_unsigned_v2f32_v2i32(<2 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f32_v2i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f32_v2i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SME-NEXT:    ret
; CHECK-FPRCVT-LABEL: test_unsigned_v2f32_v2i32:
    %x = call <2 x i32> @llvm.fptoui.sat.v2f32.v2i32(<2 x float> %f)
    ret <2 x i32> %x
}

define <3 x i32> @test_unsigned_v3f32_v3i32(<3 x float> %f) {
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v3f32_v3i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <3 x i32> @llvm.fptoui.sat.v3f32.v3i32(<3 x float> %f)
    ret <3 x i32> %x
}

define <4 x i32> @test_unsigned_v4f32_v4i32(<4 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f32_v4i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f32_v4i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i32> @llvm.fptoui.sat.v4f32.v4i32(<4 x float> %f)
    ret <4 x i32> %x
}

define <6 x i32> @test_unsigned_v6f32_v6i32(<6 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v6f32_v6i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $s2 killed $s2 def $z2
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $s0 killed $s0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $s3 killed $s3 def $z3
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $s1 killed $s1 def $z1
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $s5 killed $s5 def $z5
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $s4 killed $s4 def $z4
; CHECK-FPRCVT-SVE-NEXT:    zip1 z2.s, z2.s, z3.s
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    zip1 z1.s, z4.s, z5.s
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.d, z0.d, z2.d
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    mov z2.s, z1.s[1]
; CHECK-FPRCVT-SVE-NEXT:    fmov w4, s1
; CHECK-FPRCVT-SVE-NEXT:    mov z3.s, z0.s[1]
; CHECK-FPRCVT-SVE-NEXT:    mov z4.s, z0.s[2]
; CHECK-FPRCVT-SVE-NEXT:    mov z5.s, z0.s[3]
; CHECK-FPRCVT-SVE-NEXT:    fmov w0, s0
; CHECK-FPRCVT-SVE-NEXT:    fmov w5, s2
; CHECK-FPRCVT-SVE-NEXT:    fmov w1, s3
; CHECK-FPRCVT-SVE-NEXT:    fmov w2, s4
; CHECK-FPRCVT-SVE-NEXT:    fmov w3, s5
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v6f32_v6i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $s2 killed $s2 def $z2
; CHECK-FPRCVT-SME-NEXT:    // kill: def $s0 killed $s0 def $z0
; CHECK-FPRCVT-SME-NEXT:    // kill: def $s3 killed $s3 def $z3
; CHECK-FPRCVT-SME-NEXT:    // kill: def $s1 killed $s1 def $z1
; CHECK-FPRCVT-SME-NEXT:    // kill: def $s5 killed $s5 def $z5
; CHECK-FPRCVT-SME-NEXT:    // kill: def $s4 killed $s4 def $z4
; CHECK-FPRCVT-SME-NEXT:    zip1 z2.s, z2.s, z3.s
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    zip1 z1.s, z4.s, z5.s
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.d, z0.d, z2.d
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    mov z2.s, z1.s[1]
; CHECK-FPRCVT-SME-NEXT:    fmov w4, s1
; CHECK-FPRCVT-SME-NEXT:    mov z3.s, z0.s[1]
; CHECK-FPRCVT-SME-NEXT:    mov z4.s, z0.s[2]
; CHECK-FPRCVT-SME-NEXT:    mov z5.s, z0.s[3]
; CHECK-FPRCVT-SME-NEXT:    fmov w0, s0
; CHECK-FPRCVT-SME-NEXT:    fmov w5, s2
; CHECK-FPRCVT-SME-NEXT:    fmov w1, s3
; CHECK-FPRCVT-SME-NEXT:    fmov w2, s4
; CHECK-FPRCVT-SME-NEXT:    fmov w3, s5
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <6 x i32> @llvm.fptoui.sat.v6f32.v6i32(<6 x float> %f)
    ret <6 x i32> %x
}

define <8 x i32> @test_unsigned_v8f32_v8i32(<8 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v8f32_v8i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v8f32_v8i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <8 x i32> @llvm.fptoui.sat.v8f32.v8i32(<8 x float> %f)
    ret <8 x i32> %x
}

;
; Double to unsigned 32-bit -- Vector size variation
;

define <1 x i32> @test_unsigned_v1f64_v1i32(<1 x double> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v1f64_v1i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w8, d0
; CHECK-FPRCVT-SVE-NEXT:    mov z0.s, w8
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v1f64_v1i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w8, d0
; CHECK-FPRCVT-SME-NEXT:    mov z0.s, w8
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <1 x i32> @llvm.fptoui.sat.v1f64.v1i32(<1 x double> %f)
    ret <1 x i32> %x
}

define <2 x i32> @test_unsigned_v2f64_v2i32(<2 x double> %f) {
 test_unsigned_v2f64_v2i32:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f64_v2i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w8, d0
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w9, d1
; CHECK-FPRCVT-SVE-NEXT:    fmov s0, w8
; CHECK-FPRCVT-SVE-NEXT:    fmov s1, w9
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f64_v2i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SME-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w8, d0
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w9, d1
; CHECK-FPRCVT-SME-NEXT:    fmov s0, w8
; CHECK-FPRCVT-SME-NEXT:    fmov s1, w9
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i32> @llvm.fptoui.sat.v2f64.v2i32(<2 x double> %f)
    ret <2 x i32> %x
}

define <3 x i32> @test_unsigned_v3f64_v3i32(<3 x double> %f) {
 test_unsigned_v3f64_v3i32:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v3f64_v3i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w8, d0
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w9, d2
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w10, d1
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w11, d0
; CHECK-FPRCVT-SVE-NEXT:    fmov s0, w8
; CHECK-FPRCVT-SVE-NEXT:    fmov s1, w9
; CHECK-FPRCVT-SVE-NEXT:    fmov s2, w10
; CHECK-FPRCVT-SVE-NEXT:    fmov s3, w11
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.s, z1.s, z0.s
; CHECK-FPRCVT-SVE-NEXT:    zip1 z1.s, z3.s, z2.s
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.d, z1.d, z0.d
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v3f64_v3i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w8, d0
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w9, d2
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w10, d1
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w11, d0
; CHECK-FPRCVT-SME-NEXT:    fmov s0, w8
; CHECK-FPRCVT-SME-NEXT:    fmov s1, w9
; CHECK-FPRCVT-SME-NEXT:    fmov s2, w10
; CHECK-FPRCVT-SME-NEXT:    fmov s3, w11
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.s, z1.s, z0.s
; CHECK-FPRCVT-SME-NEXT:    zip1 z1.s, z3.s, z2.s
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.d, z1.d, z0.d
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <3 x i32> @llvm.fptoui.sat.v3f64.v3i32(<3 x double> %f)
    ret <3 x i32> %x
}

define <4 x i32> @test_unsigned_v4f64_v4i32(<4 x double> %f) {
 test_unsigned_v4f64_v4i32:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f64_v4i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q1 killed $q1 def $z1
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    mov z2.d, z1.d[1]
; CHECK-FPRCVT-SVE-NEXT:    mov z3.d, z0.d[1]
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w8, d1
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w10, d0
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w9, d2
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w11, d3
; CHECK-FPRCVT-SVE-NEXT:    fmov s0, w8
; CHECK-FPRCVT-SVE-NEXT:    fmov s2, w10
; CHECK-FPRCVT-SVE-NEXT:    fmov s1, w9
; CHECK-FPRCVT-SVE-NEXT:    fmov s3, w11
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    zip1 z1.s, z2.s, z3.s
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.d, z1.d, z0.d
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f64_v4i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q1 killed $q1 def $z1
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SME-NEXT:    mov z2.d, z1.d[1]
; CHECK-FPRCVT-SME-NEXT:    mov z3.d, z0.d[1]
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w8, d1
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w10, d0
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w9, d2
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w11, d3
; CHECK-FPRCVT-SME-NEXT:    fmov s0, w8
; CHECK-FPRCVT-SME-NEXT:    fmov s2, w10
; CHECK-FPRCVT-SME-NEXT:    fmov s1, w9
; CHECK-FPRCVT-SME-NEXT:    fmov s3, w11
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    zip1 z1.s, z2.s, z3.s
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.d, z1.d, z0.d
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i32> @llvm.fptoui.sat.v4f64.v4i32(<4 x double> %f)
    ret <4 x i32> %x
}

define <5 x i32> @test_unsigned_v5f64_v5i32(<5 x double> %f) {
 test_unsigned_v5f64_v5i32:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v5f64_v5i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w0, d0
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w1, d1
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w2, d2
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w3, d3
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w4, d4
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v5f64_v5i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w0, d0
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w1, d1
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w2, d2
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w3, d3
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w4, d4
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <5 x i32> @llvm.fptoui.sat.v5f64.v5i32(<5 x double> %f)
    ret <5 x i32> %x
}

;
; FP16 to unsigned 32-bit -- Vector size variation
;
define <2 x i32> @test_unsigned_v2f16_v2i32(<2 x half> %f) {
 test_unsigned_v2f16_v2i32:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f16_v2i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f16_v2i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SME-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $q0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i32> @llvm.fptoui.sat.v2f16.v2i32(<2 x half> %f)
    ret <2 x i32> %x
}

define <3 x i32> @test_unsigned_v3f16_v3i32(<3 x half> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v3f16_v3i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v3f16_v3i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SME-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <3 x i32> @llvm.fptoui.sat.v3f16.v3i32(<3 x half> %f)
    ret <3 x i32> %x
}

define <4 x i32> @test_unsigned_v4f16_v4i32(<4 x half> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f16_v4i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f16_v4i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SME-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i32> @llvm.fptoui.sat.v4f16.v4i32(<4 x half> %f)
    ret <4 x i32> %x
}

define <5 x i32> @test_unsigned_v5f16_v5i32(<5 x half> %f) {
 test_unsigned_v5f16_v5i32:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v5f16_v5i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    movprfx z1, z0
; CHECK-FPRCVT-SVE-NEXT:    ext z1.b, z1.b, z0.b, #8
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z1.s, z1.h
; CHECK-FPRCVT-SVE-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvt z1.s, p0/m, z1.h
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SVE-NEXT:    mov z2.s, z0.s[1]
; CHECK-FPRCVT-SVE-NEXT:    mov z3.s, z0.s[2]
; CHECK-FPRCVT-SVE-NEXT:    mov z4.s, z0.s[3]
; CHECK-FPRCVT-SVE-NEXT:    fmov w0, s0
; CHECK-FPRCVT-SVE-NEXT:    fmov w4, s1
; CHECK-FPRCVT-SVE-NEXT:    fmov w1, s2
; CHECK-FPRCVT-SVE-NEXT:    fmov w2, s3
; CHECK-FPRCVT-SVE-NEXT:    fmov w3, s4
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v5f16_v5i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SME-NEXT:    movprfx z1, z0
; CHECK-FPRCVT-SME-NEXT:    ext z1.b, z1.b, z0.b, #8
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SME-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SME-NEXT:    uunpklo z1.s, z1.h
; CHECK-FPRCVT-SME-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvt z1.s, p0/m, z1.h
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SME-NEXT:    mov z2.s, z0.s[1]
; CHECK-FPRCVT-SME-NEXT:    mov z3.s, z0.s[2]
; CHECK-FPRCVT-SME-NEXT:    mov z4.s, z0.s[3]
; CHECK-FPRCVT-SME-NEXT:    fmov w0, s0
; CHECK-FPRCVT-SME-NEXT:    fmov w4, s1
; CHECK-FPRCVT-SME-NEXT:    fmov w1, s2
; CHECK-FPRCVT-SME-NEXT:    fmov w2, s3
; CHECK-FPRCVT-SME-NEXT:    fmov w3, s4
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <5 x i32> @llvm.fptoui.sat.v5f16.v5i32(<5 x half> %f)
    ret <5 x i32> %x
}

define <6 x i32> @test_unsigned_v6f16_v6i32(<6 x half> %f) {
 test_unsigned_v6f16_v6i32:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v6f16_v6i32:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    movprfx z1, z0
; CHECK-FPRCVT-SVE-NEXT:    ext z1.b, z1.b, z0.b, #8
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z1.s, z1.h
; CHECK-FPRCVT-SVE-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvt z1.s, p0/m, z1.h
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SVE-NEXT:    mov z2.s, z0.s[1]
; CHECK-FPRCVT-SVE-NEXT:    mov z3.s, z0.s[2]
; CHECK-FPRCVT-SVE-NEXT:    mov z4.s, z0.s[3]
; CHECK-FPRCVT-SVE-NEXT:    fmov w0, s0
; CHECK-FPRCVT-SVE-NEXT:    mov z5.s, z1.s[1]
; CHECK-FPRCVT-SVE-NEXT:    fmov w4, s1
; CHECK-FPRCVT-SVE-NEXT:    fmov w1, s2
; CHECK-FPRCVT-SVE-NEXT:    fmov w2, s3
; CHECK-FPRCVT-SVE-NEXT:    fmov w3, s4
; CHECK-FPRCVT-SVE-NEXT:    fmov w5, s5
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v6f16_v6i32:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SME-NEXT:    movprfx z1, z0
; CHECK-FPRCVT-SME-NEXT:    ext z1.b, z1.b, z0.b, #8
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SME-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SME-NEXT:    uunpklo z1.s, z1.h
; CHECK-FPRCVT-SME-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvt z1.s, p0/m, z1.h
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SME-NEXT:    mov z2.s, z0.s[1]
; CHECK-FPRCVT-SME-NEXT:    mov z3.s, z0.s[2]
; CHECK-FPRCVT-SME-NEXT:    mov z4.s, z0.s[3]
; CHECK-FPRCVT-SME-NEXT:    fmov w0, s0
; CHECK-FPRCVT-SME-NEXT:    mov z5.s, z1.s[1]
; CHECK-FPRCVT-SME-NEXT:    fmov w4, s1
; CHECK-FPRCVT-SME-NEXT:    fmov w1, s2
; CHECK-FPRCVT-SME-NEXT:    fmov w2, s3
; CHECK-FPRCVT-SME-NEXT:    fmov w3, s4
; CHECK-FPRCVT-SME-NEXT:    fmov w5, s5
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <6 x i32> @llvm.fptoui.sat.v6f16.v6i32(<6 x half> %f)
    ret <6 x i32> %x
}

;
; 2-Vector float to unsigned integer -- result size variation
;

define <2 x i1> @test_unsigned_v2f32_v2i1(<2 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f32_v2i1:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, z0.s, #1
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f32_v2i1:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, z0.s, #1
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i1> @llvm.fptoui.sat.v2f32.v2i1(<2 x float> %f)
    ret <2 x i1> %x
}

define <2 x i8> @test_unsigned_v2f32_v2i8(<2 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f32_v2i8:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, z0.s, #255
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f32_v2i8:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, z0.s, #255
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i8> @llvm.fptoui.sat.v2f32.v2i8(<2 x float> %f)
    ret <2 x i8> %x
}

define <2 x i13> @test_unsigned_v2f32_v2i13(<2 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f32_v2i13:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    mov z1.s, #8191 // =0x1fff
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl2
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f32_v2i13:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    mov z1.s, #8191 // =0x1fff
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl2
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i13> @llvm.fptoui.sat.v2f32.v2i13(<2 x float> %f)
    ret <2 x i13> %x
}

define <2 x i16> @test_unsigned_v2f32_v2i16(<2 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f32_v2i16:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    mov z1.s, #65535 // =0xffff
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl2
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f32_v2i16:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    mov z1.s, #65535 // =0xffff
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl2
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i16> @llvm.fptoui.sat.v2f32.v2i16(<2 x float> %f)
    ret <2 x i16> %x
}

define <2 x i19> @test_unsigned_v2f32_v2i19(<2 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f32_v2i19:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    mov z1.s, #0x7ffff
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl2
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f32_v2i19:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    mov z1.s, #0x7ffff
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl2
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i19> @llvm.fptoui.sat.v2f32.v2i19(<2 x float> %f)
    ret <2 x i19> %x
}

define <2 x i32> @test_unsigned_v2f32_v2i32_duplicate(<2 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f32_v2i32_duplicate:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f32_v2i32_duplicate:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.2s, v0.2s
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i32> @llvm.fptoui.sat.v2f32.v2i32(<2 x float> %f)
    ret <2 x i32> %x
}


define <2 x i64> @test_unsigned_v2f32_v2i64(<2 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f32_v2i64:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.d, vl2
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z0.d, z0.s
; CHECK-FPRCVT-SVE-NEXT:    fcvt z0.d, p0/m, z0.s
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.2d, v0.2d
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f32_v2i64:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.d, vl2
; CHECK-FPRCVT-SME-NEXT:    uunpklo z0.d, z0.s
; CHECK-FPRCVT-SME-NEXT:    fcvt z0.d, p0/m, z0.s
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.2d, v0.2d
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i64> @llvm.fptoui.sat.v2f32.v2i64(<2 x float> %f)
    ret <2 x i64> %x
}

;
; 4-Vector float to unsigned integer -- result size variation
;

define <4 x i1> @test_unsigned_v4f32_v4i1(<4 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f32_v4i1:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, z0.s, #1
; CHECK-FPRCVT-SVE-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f32_v4i1:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, z0.s, #1
; CHECK-FPRCVT-SME-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
; CHECK-FPRCVT-LABEL: test_unsigned_v4f32_v4i1:
    %x = call <4 x i1> @llvm.fptoui.sat.v4f32.v4i1(<4 x float> %f)
    ret <4 x i1> %x
}

define <4 x i8> @test_unsigned_v4f32_v4i8(<4 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f32_v4i8:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, z0.s, #255
; CHECK-FPRCVT-SVE-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f32_v4i8:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, z0.s, #255
; CHECK-FPRCVT-SME-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i8> @llvm.fptoui.sat.v4f32.v4i8(<4 x float> %f)
    ret <4 x i8> %x
}

define <4 x i13> @test_unsigned_v4f32_v4i13(<4 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f32_v4i13:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    mov z1.s, #8191 // =0x1fff
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f32_v4i13:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    mov z1.s, #8191 // =0x1fff
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i13> @llvm.fptoui.sat.v4f32.v4i13(<4 x float> %f)
    ret <4 x i13> %x
}

define <4 x i16> @test_unsigned_v4f32_v4i16(<4 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f32_v4i16:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    mov z1.s, #65535 // =0xffff
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f32_v4i16:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    mov z1.s, #65535 // =0xffff
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
; CHECK-FPRCVT-LABEL: test_unsigned_v4f32_v4i16:
    %x = call <4 x i16> @llvm.fptoui.sat.v4f32.v4i16(<4 x float> %f)
    ret <4 x i16> %x
}

define <4 x i19> @test_unsigned_v4f32_v4i19(<4 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f32_v4i19:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    mov z1.s, #0x7ffff
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f32_v4i19:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    mov z1.s, #0x7ffff
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i19> @llvm.fptoui.sat.v4f32.v4i19(<4 x float> %f)
    ret <4 x i19> %x
}

define <4 x i32> @test_unsigned_v4f32_v4i32_duplicate(<4 x float> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f32_v4i32_duplicate:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f32_v4i32_duplicate:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i32> @llvm.fptoui.sat.v4f32.v4i32(<4 x float> %f)
    ret <4 x i32> %x
}


define <4 x i64> @test_unsigned_v4f32_v4i64(<4 x float> %f) {
 test_unsigned_v4f32_v4i64:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f32_v4i64:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    movprfx z1, z0
; CHECK-FPRCVT-SVE-NEXT:    ext z1.b, z1.b, z0.b, #8
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.d, vl2
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z0.d, z0.s
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z1.d, z1.s
; CHECK-FPRCVT-SVE-NEXT:    fcvt z0.d, p0/m, z0.s
; CHECK-FPRCVT-SVE-NEXT:    fcvt z1.d, p0/m, z1.s
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.2d, v0.2d
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v1.2d, v1.2d
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f32_v4i64:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SME-NEXT:    movprfx z1, z0
; CHECK-FPRCVT-SME-NEXT:    ext z1.b, z1.b, z0.b, #8
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.d, vl2
; CHECK-FPRCVT-SME-NEXT:    uunpklo z0.d, z0.s
; CHECK-FPRCVT-SME-NEXT:    uunpklo z1.d, z1.s
; CHECK-FPRCVT-SME-NEXT:    fcvt z0.d, p0/m, z0.s
; CHECK-FPRCVT-SME-NEXT:    fcvt z1.d, p0/m, z1.s
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.2d, v0.2d
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v1.2d, v1.2d
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i64> @llvm.fptoui.sat.v4f32.v4i64(<4 x float> %f)
    ret <4 x i64> %x
}


;
; 2-Vector double to unsigned integer -- result size variation
;

define <2 x i1> @test_unsigned_v2f64_v2i1(<2 x double> %f) {
 test_unsigned_v2f64_v2i1:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f64_v2i1:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w8, d0
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w9, d1
; CHECK-FPRCVT-SVE-NEXT:    cmp w8, #1
; CHECK-FPRCVT-SVE-NEXT:    csinc w8, w8, wzr, lo
; CHECK-FPRCVT-SVE-NEXT:    fmov s0, w8
; CHECK-FPRCVT-SVE-NEXT:    cmp w9, #1
; CHECK-FPRCVT-SVE-NEXT:    csinc w9, w9, wzr, lo
; CHECK-FPRCVT-SVE-NEXT:    fmov s1, w9
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f64_v2i1:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SME-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w8, d0
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w9, d1
; CHECK-FPRCVT-SME-NEXT:    cmp w8, #1
; CHECK-FPRCVT-SME-NEXT:    csinc w8, w8, wzr, lo
; CHECK-FPRCVT-SME-NEXT:    fmov s0, w8
; CHECK-FPRCVT-SME-NEXT:    cmp w9, #1
; CHECK-FPRCVT-SME-NEXT:    csinc w9, w9, wzr, lo
; CHECK-FPRCVT-SME-NEXT:    fmov s1, w9
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
; CHECK-FPRCVT-NEXT:    ret
    %x = call <2 x i1> @llvm.fptoui.sat.v2f64.v2i1(<2 x double> %f)
    ret <2 x i1> %x
}

define <2 x i8> @test_unsigned_v2f64_v2i8(<2 x double> %f) {
 test_unsigned_v2f64_v2i8:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f64_v2i8:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w9, d0
; CHECK-FPRCVT-SVE-NEXT:    mov w8, #255 // =0xff
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w10, d1
; CHECK-FPRCVT-SVE-NEXT:    cmp w9, #255
; CHECK-FPRCVT-SVE-NEXT:    csel w9, w9, w8, lo
; CHECK-FPRCVT-SVE-NEXT:    fmov s0, w9
; CHECK-FPRCVT-SVE-NEXT:    cmp w10, #255
; CHECK-FPRCVT-SVE-NEXT:    csel w8, w10, w8, lo
; CHECK-FPRCVT-SVE-NEXT:    fmov s1, w8
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f64_v2i8:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SME-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w9, d0
; CHECK-FPRCVT-SME-NEXT:    mov w8, #255 // =0xff
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w10, d1
; CHECK-FPRCVT-SME-NEXT:    cmp w9, #255
; CHECK-FPRCVT-SME-NEXT:    csel w9, w9, w8, lo
; CHECK-FPRCVT-SME-NEXT:    fmov s0, w9
; CHECK-FPRCVT-SME-NEXT:    cmp w10, #255
; CHECK-FPRCVT-SME-NEXT:    csel w8, w10, w8, lo
; CHECK-FPRCVT-SME-NEXT:    fmov s1, w8
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i8> @llvm.fptoui.sat.v2f64.v2i8(<2 x double> %f)
    ret <2 x i8> %x
}

define <2 x i13> @test_unsigned_v2f64_v2i13(<2 x double> %f) {
 test_unsigned_v2f64_v2i13:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f64_v2i13:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w9, d0
; CHECK-FPRCVT-SVE-NEXT:    mov w8, #8191 // =0x1fff
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w10, d1
; CHECK-FPRCVT-SVE-NEXT:    cmp w9, w8
; CHECK-FPRCVT-SVE-NEXT:    csel w9, w9, w8, lo
; CHECK-FPRCVT-SVE-NEXT:    fmov s0, w9
; CHECK-FPRCVT-SVE-NEXT:    cmp w10, w8
; CHECK-FPRCVT-SVE-NEXT:    csel w8, w10, w8, lo
; CHECK-FPRCVT-SVE-NEXT:    fmov s1, w8
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f64_v2i13:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SME-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w9, d0
; CHECK-FPRCVT-SME-NEXT:    mov w8, #8191 // =0x1fff
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w10, d1
; CHECK-FPRCVT-SME-NEXT:    cmp w9, w8
; CHECK-FPRCVT-SME-NEXT:    csel w9, w9, w8, lo
; CHECK-FPRCVT-SME-NEXT:    fmov s0, w9
; CHECK-FPRCVT-SME-NEXT:    cmp w10, w8
; CHECK-FPRCVT-SME-NEXT:    csel w8, w10, w8, lo
; CHECK-FPRCVT-SME-NEXT:    fmov s1, w8
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i13> @llvm.fptoui.sat.v2f64.v2i13(<2 x double> %f)
    ret <2 x i13> %x
}

define <2 x i16> @test_unsigned_v2f64_v2i16(<2 x double> %f) {
 test_unsigned_v2f64_v2i16:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f64_v2i16:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w9, d0
; CHECK-FPRCVT-SVE-NEXT:    mov w8, #65535 // =0xffff
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w10, d1
; CHECK-FPRCVT-SVE-NEXT:    cmp w9, w8
; CHECK-FPRCVT-SVE-NEXT:    csel w9, w9, w8, lo
; CHECK-FPRCVT-SVE-NEXT:    fmov s0, w9
; CHECK-FPRCVT-SVE-NEXT:    cmp w10, w8
; CHECK-FPRCVT-SVE-NEXT:    csel w8, w10, w8, lo
; CHECK-FPRCVT-SVE-NEXT:    fmov s1, w8
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f64_v2i16:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SME-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w9, d0
; CHECK-FPRCVT-SME-NEXT:    mov w8, #65535 // =0xffff
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w10, d1
; CHECK-FPRCVT-SME-NEXT:    cmp w9, w8
; CHECK-FPRCVT-SME-NEXT:    csel w9, w9, w8, lo
; CHECK-FPRCVT-SME-NEXT:    fmov s0, w9
; CHECK-FPRCVT-SME-NEXT:    cmp w10, w8
; CHECK-FPRCVT-SME-NEXT:    csel w8, w10, w8, lo
; CHECK-FPRCVT-SME-NEXT:    fmov s1, w8
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i16> @llvm.fptoui.sat.v2f64.v2i16(<2 x double> %f)
    ret <2 x i16> %x
}

define <2 x i32> @test_unsigned_v2f64_v2i32_duplicate(<2 x double> %f) {
 test_unsigned_v2f64_v2i32_duplicate:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f64_v2i32_duplicate:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w8, d0
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu w9, d1
; CHECK-FPRCVT-SVE-NEXT:    fmov s0, w8
; CHECK-FPRCVT-SVE-NEXT:    fmov s1, w9
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f64_v2i32_duplicate:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SME-NEXT:    mov z1.d, z0.d[1]
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w8, d0
; CHECK-FPRCVT-SME-NEXT:    fcvtzu w9, d1
; CHECK-FPRCVT-SME-NEXT:    fmov s0, w8
; CHECK-FPRCVT-SME-NEXT:    fmov s1, w9
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i32> @llvm.fptoui.sat.v2f64.v2i32(<2 x double> %f)
    ret <2 x i32> %x
}

define <2 x i64> @test_unsigned_v2f64_v2i64(<2 x double> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v2f64_v2i64:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.2d, v0.2d
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v2f64_v2i64:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.2d, v0.2d
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <2 x i64> @llvm.fptoui.sat.v2f64.v2i64(<2 x double> %f)
    ret <2 x i64> %x
}

;
; 4-Vector half to unsigned integer -- result size variation
;

define <4 x i1> @test_unsigned_v4f16_v4i1(<4 x half> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f16_v4i1:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4h, v0.4h
; CHECK-FPRCVT-SVE-NEXT:    umin z0.h, z0.h, #1
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f16_v4i1:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4h, v0.4h
; CHECK-FPRCVT-SME-NEXT:    umin z0.h, z0.h, #1
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i1> @llvm.fptoui.sat.v4f16.v4i1(<4 x half> %f)
    ret <4 x i1> %x
}

define <4 x i8> @test_unsigned_v4f16_v4i8(<4 x half> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f16_v4i8:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4h, v0.4h
; CHECK-FPRCVT-SVE-NEXT:    umin z0.h, z0.h, #255
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f16_v4i8:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4h, v0.4h
; CHECK-FPRCVT-SME-NEXT:    umin z0.h, z0.h, #255
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i8> @llvm.fptoui.sat.v4f16.v4i8(<4 x half> %f)
    ret <4 x i8> %x
}

define <4 x i13> @test_unsigned_v4f16_v4i13(<4 x half> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f16_v4i13:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    mov z1.h, #8191 // =0x1fff
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4h, v0.4h
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.h, vl4
; CHECK-FPRCVT-SVE-NEXT:    umin z0.h, p0/m, z0.h, z1.h
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f16_v4i13:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    mov z1.h, #8191 // =0x1fff
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4h, v0.4h
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.h, vl4
; CHECK-FPRCVT-SME-NEXT:    umin z0.h, p0/m, z0.h, z1.h
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i13> @llvm.fptoui.sat.v4f16.v4i13(<4 x half> %f)
    ret <4 x i13> %x
}

define <4 x i16> @test_unsigned_v4f16_v4i16(<4 x half> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f16_v4i16:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4h, v0.4h
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f16_v4i16:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4h, v0.4h
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i16> @llvm.fptoui.sat.v4f16.v4i16(<4 x half> %f)
    ret <4 x i16> %x
}

define <4 x i19> @test_unsigned_v4f16_v4i19(<4 x half> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f16_v4i19:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SVE-NEXT:    mov z1.s, #0x7ffff
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f16_v4i19:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SME-NEXT:    mov z1.s, #0x7ffff
; CHECK-FPRCVT-SME-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, p0/m, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i19> @llvm.fptoui.sat.v4f16.v4i19(<4 x half> %f)
    ret <4 x i19> %x
}

define <4 x i32> @test_unsigned_v4f16_v4i32_duplicate(<4 x half> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v4f16_v4i32_duplicate:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v4f16_v4i32_duplicate:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SME-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <4 x i32> @llvm.fptoui.sat.v4f16.v4i32(<4 x half> %f)
    ret <4 x i32> %x
}

;
; 8-Vector half to unsigned integer -- result size variation
;

define <8 x i1> @test_unsigned_v8f16_v8i1(<8 x half> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v8f16_v8i1:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.8h, v0.8h
; CHECK-FPRCVT-SVE-NEXT:    umin z0.h, z0.h, #1
; CHECK-FPRCVT-SVE-NEXT:    uzp1 z0.b, z0.b, z0.b
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v8f16_v8i1:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.8h, v0.8h
; CHECK-FPRCVT-SME-NEXT:    umin z0.h, z0.h, #1
; CHECK-FPRCVT-SME-NEXT:    uzp1 z0.b, z0.b, z0.b
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <8 x i1> @llvm.fptoui.sat.v8f16.v8i1(<8 x half> %f)
    ret <8 x i1> %x
}

define <8 x i8> @test_unsigned_v8f16_v8i8(<8 x half> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v8f16_v8i8:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.8h, v0.8h
; CHECK-FPRCVT-SVE-NEXT:    umin z0.h, z0.h, #255
; CHECK-FPRCVT-SVE-NEXT:    uzp1 z0.b, z0.b, z0.b
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v8f16_v8i8:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.8h, v0.8h
; CHECK-FPRCVT-SME-NEXT:    umin z0.h, z0.h, #255
; CHECK-FPRCVT-SME-NEXT:    uzp1 z0.b, z0.b, z0.b
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <8 x i8> @llvm.fptoui.sat.v8f16.v8i8(<8 x half> %f)
    ret <8 x i8> %x
}

define <8 x i16> @test_unsigned_v8f16_v8i16(<8 x half> %f) {
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v8f16_v8i16:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.8h, v0.8h
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v8f16_v8i16:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.8h, v0.8h
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <8 x i16> @llvm.fptoui.sat.v8f16.v8i16(<8 x half> %f)
    ret <8 x i16> %x
}


define <8 x i32> @test_unsigned_v8f16_v8i32_duplicate(<8 x half> %f) {
 test_unsigned_v8f16_v8i32_duplicate:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v8f16_v8i32_duplicate:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SVE-NEXT:    movprfx z1, z0
; CHECK-FPRCVT-SVE-NEXT:    ext z1.b, z1.b, z0.b, #8
; CHECK-FPRCVT-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SVE-NEXT:    uunpklo z1.s, z1.h
; CHECK-FPRCVT-SVE-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SVE-NEXT:    fcvt z1.s, p0/m, z1.h
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v8f16_v8i32_duplicate:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-FPRCVT-SME-NEXT:    movprfx z1, z0
; CHECK-FPRCVT-SME-NEXT:    ext z1.b, z1.b, z0.b, #8
; CHECK-FPRCVT-SME-NEXT:    ptrue p0.s, vl4
; CHECK-FPRCVT-SME-NEXT:    uunpklo z0.s, z0.h
; CHECK-FPRCVT-SME-NEXT:    uunpklo z1.s, z1.h
; CHECK-FPRCVT-SME-NEXT:    fcvt z0.s, p0/m, z0.h
; CHECK-FPRCVT-SME-NEXT:    fcvt z1.s, p0/m, z1.h
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <8 x i32> @llvm.fptoui.sat.v8f16.v8i32(<8 x half> %f)
    ret <8 x i32> %x
}

define <8 x i8> @test_unsigned_v8f32_v8i8(<8 x float> %f) {
 test_unsigned_v8f32_v8i8:
; CHECK-FPRCVT-SVE-LABEL: test_unsigned_v8f32_v8i8:
; CHECK-FPRCVT-SVE:       // %bb.0:
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SVE-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SVE-NEXT:    umin z1.s, z1.s, #255
; CHECK-FPRCVT-SVE-NEXT:    umin z0.s, z0.s, #255
; CHECK-FPRCVT-SVE-NEXT:    uzp1 z1.h, z1.h, z1.h
; CHECK-FPRCVT-SVE-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-FPRCVT-SVE-NEXT:    mov z2.h, z1.h[3]
; CHECK-FPRCVT-SVE-NEXT:    mov z3.h, z1.h[2]
; CHECK-FPRCVT-SVE-NEXT:    mov z4.h, z1.h[1]
; CHECK-FPRCVT-SVE-NEXT:    mov z5.h, z0.h[3]
; CHECK-FPRCVT-SVE-NEXT:    mov z6.h, z0.h[2]
; CHECK-FPRCVT-SVE-NEXT:    mov z7.h, z0.h[1]
; CHECK-FPRCVT-SVE-NEXT:    zip1 z2.b, z3.b, z2.b
; CHECK-FPRCVT-SVE-NEXT:    zip1 z1.b, z1.b, z4.b
; CHECK-FPRCVT-SVE-NEXT:    zip1 z3.b, z6.b, z5.b
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.b, z0.b, z7.b
; CHECK-FPRCVT-SVE-NEXT:    zip1 z1.h, z1.h, z2.h
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.h, z0.h, z3.h
; CHECK-FPRCVT-SVE-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SVE-NEXT:    ret
;
; CHECK-FPRCVT-SME-LABEL: test_unsigned_v8f32_v8i8:
; CHECK-FPRCVT-SME:       // %bb.0:
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v1.4s, v1.4s
; CHECK-FPRCVT-SME-NEXT:    fcvtzu v0.4s, v0.4s
; CHECK-FPRCVT-SME-NEXT:    umin z1.s, z1.s, #255
; CHECK-FPRCVT-SME-NEXT:    umin z0.s, z0.s, #255
; CHECK-FPRCVT-SME-NEXT:    uzp1 z1.h, z1.h, z1.h
; CHECK-FPRCVT-SME-NEXT:    uzp1 z0.h, z0.h, z0.h
; CHECK-FPRCVT-SME-NEXT:    mov z2.h, z1.h[3]
; CHECK-FPRCVT-SME-NEXT:    mov z3.h, z1.h[2]
; CHECK-FPRCVT-SME-NEXT:    mov z4.h, z1.h[1]
; CHECK-FPRCVT-SME-NEXT:    mov z5.h, z0.h[3]
; CHECK-FPRCVT-SME-NEXT:    mov z6.h, z0.h[2]
; CHECK-FPRCVT-SME-NEXT:    mov z7.h, z0.h[1]
; CHECK-FPRCVT-SME-NEXT:    zip1 z2.b, z3.b, z2.b
; CHECK-FPRCVT-SME-NEXT:    zip1 z1.b, z1.b, z4.b
; CHECK-FPRCVT-SME-NEXT:    zip1 z3.b, z6.b, z5.b
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.b, z0.b, z7.b
; CHECK-FPRCVT-SME-NEXT:    zip1 z1.h, z1.h, z2.h
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.h, z0.h, z3.h
; CHECK-FPRCVT-SME-NEXT:    zip1 z0.s, z0.s, z1.s
; CHECK-FPRCVT-SME-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-FPRCVT-SME-NEXT:    ret
    %x = call <8 x i8> @llvm.fptoui.sat.v8f32.v8i8(<8 x float> %f)
    ret <8 x i8> %x
}

